# Generated by Django 3.1.4 on 2020-12-21 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='qiita_user_id',
            field=models.CharField(max_length=30, verbose_name='QiitaユーザーID'),
        ),
    ]
