# Generated by Django 3.1.4 on 2021-01-29 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20201222_0002'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='qiita_user_id',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Qiita_ユーザーID'),
        ),
    ]
