# Generated by Django 3.1.4 on 2021-01-29 05:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cms', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='techblog',
            name='qiita_user_id',
        ),
        migrations.AddField(
            model_name='techblog',
            name='custom_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='techblog_custom_user', to=settings.AUTH_USER_MODEL, verbose_name='投稿ユーザ'),
        ),
        migrations.AlterField(
            model_name='techblog',
            name='qiita_item_id',
            field=models.CharField(default=2, max_length=30, verbose_name='Qiita_投稿ID'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='techblog',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='更新日'),
        ),
    ]
