# Generated by Django 3.1.4 on 2021-01-29 12:49

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0002_auto_20210129_1444'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='techblog',
            name='custom_user',
        ),
        migrations.AddField(
            model_name='techblog',
            name='qiita_user_id',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Qiita_ユーザーID'),
        ),
        migrations.AlterField(
            model_name='techblog',
            name='qiita_item_id',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Qiita_投稿ID'),
        ),
        migrations.AlterField(
            model_name='techblog',
            name='updated_at',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='更新日'),
        ),
    ]
