# Generated by Django 3.1.4 on 2020-12-21 14:51

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=31, verbose_name='カテゴリ名')),
            ],
            options={
                'verbose_name_plural': '活動カテゴリ',
            },
        ),
        migrations.CreateModel(
            name='Techcategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=31, verbose_name='カテゴリ名')),
            ],
            options={
                'verbose_name_plural': '技術カテゴリ',
            },
        ),
        migrations.CreateModel(
            name='Techblog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='タイトル')),
                ('body', models.TextField(verbose_name='本文')),
                ('image', models.ImageField(blank=True, null=True, upload_to='images/', verbose_name='画像')),
                ('published_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='公開日')),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='更新日')),
                ('is_qiita', models.BooleanField(default=False, verbose_name='Qiita転載')),
                ('qiita_item_id', models.CharField(blank=True, max_length=30, null=True, verbose_name='Qiita_投稿ID')),
                ('qiita_user_id', models.CharField(blank=True, max_length=30, null=True, verbose_name='Qiita_ユーザーID')),
                ('status', models.BooleanField(default=False, verbose_name='公開ステータス')),
                ('categories', models.ManyToManyField(related_name='カテゴリ', to='cms.Techcategory')),
            ],
            options={
                'verbose_name_plural': 'Techblog(技術記事)',
            },
        ),
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='タイトル')),
                ('body', models.TextField(verbose_name='本文')),
                ('image', models.ImageField(blank=True, null=True, upload_to='images/', verbose_name='画像')),
                ('published_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='公開日')),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='更新日')),
                ('is_note', models.BooleanField(default=False, verbose_name='Note転載')),
                ('note_item_id', models.CharField(blank=True, max_length=255, null=True, verbose_name='noteキー')),
                ('status', models.BooleanField(default=False, verbose_name='公開ステータス')),
                ('categories', models.ManyToManyField(related_name='カテゴリ', to='cms.Category')),
            ],
            options={
                'verbose_name_plural': 'Activity(活動記事)',
            },
        ),
    ]
