# Generated by Django 3.1.4 on 2020-12-17 18:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='activity',
            options={'verbose_name_plural': 'Activity(活動記事)'},
        ),
        migrations.AlterModelOptions(
            name='techblog',
            options={'verbose_name_plural': 'Techblog(技術記事)'},
        ),
    ]
